# -*- coding: utf-8 -*-

DISTRITOS_NORM = {
    u'rio negro'                        : u'Río Negro',
    u'catamarca'                        : u'Catamarca',
    u'santiago del estero'              : u'Santiago del Estero',
    u'la rioja'                         : u'La Rioja',
    u'buenos aires'                     : u'Buenos Aires',
    u'cordoba'                          : u'Córdoba',
    u'santa fe'                         : u'Santa Fé',
    u'entre rios'                       : u'Entre Ríos',
    u'santa cruz'                       : u'Santa Cruz',
    u'tucuman'                          : u'Tucumán',
    u'ciudad de buenos aires'           : u'Ciudad Autónoma de Buenos Aires',
    u'ciudad autonoma de buenos aires'  : u'Ciudad Autónoma de Buenos Aires',
    u'corrientes'                       : u'Corrientes',
    u'mendoza'                          : u'Mendoza',
    u'tierra del fuego'                 : u'Tierra del Fuego',
    u'tierra del fuego, antartida e islas del atlantico sur'
                                        : u'Tierra del Fuego',
    u'jujuy'                            : u'Jujuy',
    u'san luis'                         : u'San Luis',
    u'neuquen'                          : u'Neuquen',
    u'formosa'                          : u'Formosa',
    u'chubut'                           : u'Chubut',
    u'san juan'                         : u'San Juan',
    u'salta'                            : u'Salta',
    u'chaco'                            : u'Chaco',
    u'la pampa'                         : u'La Pampa',
    u'misiones'                         : u'Misiones' }


FIRMANTES_SPECIAL_NORM = {
    u'parlamentaria mixta revisora de cuentas de la administracion' :
        u'Comisión Parlamentaria Mixta Revisora de Cuentas de la Administración',
    u'h camara de diputados':
        u'Cámara de Diputados',
    u'bicameral permanente de tramite legislativo - ley 26122':
        u'Comisión Bicamiral Permanente de Trámite Legislativo' }


BLOQUES_NORM = {
    u'accion republica'                                    : u'Acción Republicana',
    u'alianza coalicion civica'                            : u'Alianza Coalición Cívica',
    u'ari autonomo 8 +'                                    : u'ARI Autónomo 8 +',
    u'ari'                                                 : u'ARI',
    u'autodeterminacion y libertad'                        : u'Autodeterminación y Libertad',
    u'bloque buenos aires'                                 : u'Bloque Buenos Aires',
    u'bloque tucuman'                                      : u'Bloque Tucumán',
    u'buenos aires para todos en proyecto sur'             : u'Buenos Aires para Todos en Proyecto Sur',
    u'buenos aires por el cambio'                          : u'Buenos Aires por el Cambio',
    u'coalicion civica - ari - gen - upt'                  : u'Coalición Cívica - ARI - GEN - UPT',
    u'coalicion civica - ari'                              : u'Coalición Cívica - ARI',
    u'coalicion civica'                                    : u'Alianza Coalición Cívica',
    u'compromiso para el cambio'                           : u'Compromiso para el Cambio',
    u'concertacion entrerriana'                            : u'Concertación Entrerriana',
    u'concertacion plural'                                 : u'Concertación Plural',
    u'consenso federal'                                    : u'Consenso Federal',
    u'convergencia federal'                                : u'Convergencia Federal',
    u'convergencia'                                        : u'Convergencia',
    u'cordoba federal'                                     : u'Córdoba Federal',
    u'corriente de pensamiento federal'                    : u'Corriente de Pensamiento Federal',
    u'corriente peronista federal'                         : u'Corriente Peronista Federal',
    u'cruzada renov'                                       : u'Cruzada Renovadora',
    u'de la concertacion'                                  : u'De la Concertación',
    u'democracia igualitaria y participativa (d.i.p.)'     : u'Democracia Igualitaria y Participativa (D.I.P.)',
    u'democrata de mendoza'                                : u'Demócrata de Mendoza',
    u'democrata progresista'                               : u'Demócrata prograsista',
    u'democrata'                                           : u'Demócrata',
    u'dialogo por buenos aires'                            : u'Dialogo por Buenos Aires',
    u'dignidad peronista'                                  : u'Dignidad Peronista',
    u'dignidad y justicia'                                 : u'Dignidad y Justicia',
    u'emancipacion y justicia'                             : u'Emancipacion y Justicia',
    u'encuentro de los rionegrinos'                        : u'Encuentro de los Rionegrinos',
    u'encuentro popular'                                   : u'Encuentro Popular',
    u'encuentro popular y social'                          : u'Encuentro Popular y Social',
    u'encuentro'                                           : u'Encuentro',
    u'esperanza federal'                                   : u'Esperanza Federal',
    u'eva peron'                                           : u'Eva Perón',
    u'federalismo santafesino'                             : u'Federalismo Santafesino',
    u'federalismo y liberacion'                            : u'Federalismo y Liberacion',
    u'federal santafesino'                                 : u'Federal Santafesino',
    u'fiscal'                                              : u'Fiscal',
    u'frente civico - cordoba'                             : u'Frente Cívico - Córdoba',
    u'frente civico de la provincia de cordoba'            : u'Frente Civico de la Provincia de Cordoba',
    u'frente civico jujeño'                                : u'Frente Cívico Jujeño',
    u'frente civico por santiago'                          : u'Frente Cívico por Santiago',
    u'frente civico tucuman'                               : u'Frente Cívico Tucumán',
    u'frente civico y social de catamarca'                 : u'Frente Cívico y Social de Catamarca',
    u'frente civico y social'                              : u'Frente Cívico y Social',
    u'frente del movimiento popular'                       : u'Frente del Movimiento Popular',
    u'frente de todos'                                     : u'Frente De Todos',
    u'frente de unidad provincial'                         : u'Frente de Unidad Provincial',
    u'frente grande'                                       : u'Frente Grande',
    u'frente justicia union y libertad - frejuli'          : u'Frente Justicia Unión y Libertad - FREJULI',
    u'frente movimiento popular'                           : u'Frente Movimiento Popular',
    u'frente para el cambio'                               : u'Frente Para el Cambio',
    u'frente para la victoria - partido bloquista'         : u'Frente para la Victoria - Partido Bloquista',
    u'frente para la victoria - pj'                        : u'Frente para la Victoria - PJ',
    u'frente peronista federal'                            : u'Frente Peronista Federal',
    u'frente peronista'                                    : u'Frente Peronista',
    u'frente popular bonaerense'                           : u'Frente Popular Bonaerense',
    u'frente por los derechos ciudadanos'                  : u'Frente por los Derechos Ciudadanos',
    u'frente produccion y trabajo'                         : u'Frente Producción y Trabajo',
    u'frepaso'                                             : u'FREPASO',
    u'fza republicana'                                     : u'Fuerza Republicana',
    u'gen'                                                 : u'GEN',
    u'guardia peronista'                                   : u'Guardia Peronista',
    u'izquierda unida'                                     : u'Izquierda Unida',
    u'justicialismo republicano'                           : u'Justicialismo Republicano',
    u'justicialista 17 de octubre'                         : u'Justicialista 17 de Octubre',
    u'justicialista 8 de octubre'                          : u'Justicialista 8 de Octubre',
    u'justicialista dialog ar'                             : u'Justicialista DIALOG AR',
    u'justicialista nacional'                              : u'Justicialista Nacional',
    u'justicialista para el dialogo de los argentinos'     : u'Justicialista para el Dialogo de los Argentinos',
    u'justicialista san luis'                              : u'Justicialista San Luis',
    u'justicialista'                                       : u'Justicialista',
    u'la argentina de los valores'                         : u'La Argentina de los Valores',
    u'lealtad y dignidad justicialista'                    : u'Lealtad y Dignidad Justicialista',
    u'libres del sur'                                      : u'Libres del Sur',
    u'memoria y democracia'                                : u'Memoria y Democracia',
    u'mmta'                                                : u'MMTA',
    u'movimiento independiente'                            : u'Movimiento Independiente',
    u'movimiento pampa sur'                                : u'Movimiento Pampa Sur',
    u'movimiento popular neuquino'                         : u'Movimiento Popular Neuquino',
    u'movimiento proyecto sur'                             : u'Movimiento Proyecto Sur',
    u'mov pop fueguino'                                    : u'Movimiento Popular Fueguino',
    u'mov pop neuquino'                                    : u'Movimiento Popular Neuquino',
    u'nacional sindical'                                   : u'Nacional Sindical',
    u'no integra bloque'                                   : None,
    u'-'                                                   : None,
    u'nucleo unidad peronista'                             : u'Nucleo Unidad Peronista',
    u'nuevo encuentro popular y solidario'                 : u'Nuevo Encuentro Popular y Solidario',
    u'nuevo encuentro'                                     : u'Nuevo Encuentro',
    u'nuevo espacio entrerriano'                           : u'Nuevo Espacio Entrerriano',
    u'partido de la concertacion - forja'                  : u'Partido de la Concertación - Forja',
    u'partido de la victoria'                              : u'Partido de la Victoria',
    u'partido federal fueguino'                            : u'Partido Federal Fueguino',
    u'partido intransigente'                               : u'Partido Intransigente',
    u'partido justicialista la pampa'                      : u'Partido Justicialista La Pampa',
    u'partido liberal de corrientes'                       : u'Partido Liberal de Corrientes',
    u'partido nuevo contra corrup. por honest. y transp.'  : u'Partido Nuevo contra Corrupción por la Honestidad y la Transparencia',
    u'partido nuevo'                                       : u'Partido Nuevo',
    u'partido renovador de salta'                          : u'Partido Renovador de Salta',
    u'partido socialista'                                  : u'Partido Socialista',
    u'peronismo federal'                                   : u'Peronismo Federal',
    u'peronismo jujeno'                                    : u'Peronismo Jujeño',
    u'peronismo peronista'                                 : u'Peronismo Peronista',
    u'peronismo popular'                                   : u'Peronismo Popular',
    u'peronista cordoba ciudadana'                         : u'Peronista Córdoba Ciudadana',
    u'peronista federal'                                   : u'Peronista Federal',
    u'peronista salteno'                                   : u'Peronista Salteño',
    u'peronista'                                           : u'Peronista',
    u'pj frente para la victoria'                          : u'PJ - Frente para la Victoria',
    u'polo social'                                         : u'Polo Social',
    u'por la verdad'                                       : u'Por la Verdad',
    u'por tierra del fuego'                                : u'Por Tierra del Fuego',
    u'produccion y trabajo'                                : u'Produccion y Trabajo',
    u'propuesta peronista'                                 : u'Propuesta Peronista',
    u'propuesta republicana'                               : u'Propuesta Republicana',
    u'pro'                                                 : u'PRO',
    u'proyecto buenos aires federal'                       : u'Proyecto Buenos Aires Federal',
    u'proyecto corrientes'                                 : u'Proyecto Corrientes',
    u'proyecto progresista'                                : u'Proyecto Progresista',
    u'proyecto social alternativo'                         : u'Proyecto Social Alternativo',
    u'puntano independiente'                               : u'Puntano Independiente',
    u'radical independiente'                               : u'Radical Independiente',
    u'radical rionegrino'                                  : u'Radical Rionegrino',
    u'recrear para el crecimiento'                         : u'Recrear para el Crecimiento',
    u'redes'                                               : u'Renovación y Desarrollo Social (REDES)',
    u'renovador de salta'                                  : u'Renovador de Salta',
    u'renovador'                                           : u'Renovador',
    u'salta somos todos'                                   : u'Salta Somos Todos',
    u'santa fe en movimiento'                              : u'Santa Fé en Movimiento',
    u'santa fe federal'                                    : u'Santa Fé Federal',
    u'si por la unidad popular'                            : u'SI por la Unidad Popular',
    u'soberania popular'                                   : u'Soberania Popular',
    u'socialista del mijd'                                 : u'Socialista del MIJD',
    u'social patagonico'                                   : u'Social Patagonico',
    u'solidaridad e igualdad (si) - ari (t.d.f.)'          : u'Solaridad e Igualdad (SI) - ARI (TDF)',
    u'solidaridad e igualdad (si) - ari (tdf)   '          : u'Solaridad e Igualdad (SI) - ARI (TDF)',
    u'solidaridad e igualdad (si) - proyecto progresista'  : u'Solaridad e Igualdad (SI) - Proyecto Progresista',
    u'solidaridad e igualdad (si)'                         : u'Solaridad e Igualdad (SI)',
    u'trabajo y dignidad'                                  : u'Trabajo y Dignidad',
    u'ucede'                                               : u'UCEDE',
    u'ucr'                                                 : u'Unión Civica Radical',
    u'udeso salta'                                         : u'UDESO Salta',
    u'unidad federalista'                                  : u'Unidad Federalista',
    u'unidad para el desarrollo social y la equidad'       : u'Unidad para el Desarrollo Social y la Equidad',
    u'unidad popular'                                      : u'Unidad Popular',
    u'union celeste y blanca'                              : u'Unión Celeste y Blanca',
    u'union celeste y blanco'                              : u'Unión Celeste y Blanco',
    u'union civica radical'                                : u'Unión Civica Radical',
    u'union peronista'                                     : u'Unión Peronista',
    u'union por argentina'                                 : u'Unión por Argentina',
    u'union por san juan'                                  : u'Unión por San Juan',
    u'union por todos'                                     : u'Union por Todos',
    u"unipersonal 'ricardo balbin'"                        : u'Unipersonal Ricardo Balbin',
    u'unipersonal'                                         : u'Unipersonal',
    u'valores para mi pais'                                : u'Valores para mi País',
    u'vecinalista - partido nuevo'                         : u'Vecinalista - Partido Nuevo',
    u'vida y compromiso'                                   : u'Vida y Compromiso'
    }
