# -*- coding: utf8 -*-

DISTRITOS_NORM = {
    u'rio negro'                        : u'Río Negro',
    u'catamarca'                        : u'Catamarca',
    u'santiago del estero'              : u'Santiago del Estero',
    u'la rioja'                         : u'La Rioja',
    u'buenos aires'                     : u'Buenos Aires',
    u'cordoba'                          : u'Córdoba',
    u'santa fe'                         : u'Santa Fé',
    u'entre rios'                       : u'Entre Ríos',
    u'santa cruz'                       : u'Santa Cruz',
    u'tucuman'                          : u'Tucumán',
    u'ciudad de buenos aires'           : u'Ciudad Autónoma de Buenos Aires',
    u'ciudad autonoma de buenos aires'  : u'Ciudad Autónoma de Buenos Aires',
    u'corrientes'                       : u'Corrientes',
    u'mendoza'                          : u'Mendoza',
    u'tierra del fuego'                 : u'Tierra del Fuego',
    u'tierra del fuego, antartida e islas del atlantico sur'
                                        : u'Tierra del Fuego',
    u'jujuy'                            : u'Jujuy',
    u'san luis'                         : u'San Luis',
    u'neuquen'                          : u'Neuquen',
    u'formosa'                          : u'Formosa',
    u'chubut'                           : u'Chubut',
    u'san juan'                         : u'San Juan',
    u'salta'                            : u'Salta',
    u'chaco'                            : u'Chaco',
    u'la pampa'                         : u'La Pampa',
    u'misiones'                         : u'Misiones' }


FIRMANTES_SPECIAL_NORM = {
    u'parlamentaria mixta revisora de cuentas de la administracion' :
        u'Comisión Parlamentaria Mixta Revisora de Cuentas de la Administración',
    u'h camara de diputados':
        u'Cámara de Diputados',
    u'bicameral permanente de tramite legislativo - ley 26122':
        u'Comisión Bicamiral Permanente de Trámite Legislativo' }


BLOQUES_NORM = {
    u'accion republica'                                    : u'Acción Republicana',
    u'alianza coalicion civica'                            : u'Alianza Coalición Cívica',
    u'ari autonomo 8 +'                                    : u'ARI Autónomo 8 +',
    u'ari'                                                 : u'ARI',
    u'bloque tucuman'                                      : u'Bloque Tucumán',
    u'buenos aires para todos en proyecto sur'             : u'Buenos Aires para Todos en Proyecto Sur',
    u'buenos aires por el cambio'                          : u'Buenos Aires por el Cambio',
    u'coalicion civica - ari - gen - upt'                  : u'Coalición Cívica - ARI - GEN - UPT',
    u'coalicion civica'                                    : u'Alianza Coalición Cívica',
    u'concertacion entrerriana'                            : u'Concertación Entrerriana',
    u'concertacion plural'                                 : u'Concertación Plural',
    u'consenso federal'                                    : u'Consenso Federal',
    u'convergencia federal'                                : u'Convergencia Federal',
    u'convergencia'                                        : u'Convergencia',
    u'cordoba federal'                                     : u'Córdoba Federal',
    u'corriente de pensamiento federal'                    : u'Corriente de Pensamiento Federal',
    u'corriente peronista federal'                         : u'Corriente Peronista Federal',
    u'de la concertacion'                                  : u'De la Concertación',
    u'democrata de mendoza'                                : u'Demócrata de Mendoza',
    u'democrata progresista'                               : u'Demócrata prograsista',
    u'dialogo por buenos aires'                            : u'Dialogo por Buenos Aires',
    u'dignidad peronista'                                  : u'Dignidad Peronista',
    u'emancipacion y justicia'                             : u'Emancipacion y Justicia',
    u'encuentro de los rionegrinos'                        : u'Encuentro de los Rionegrinos',
    u'encuentro popular y social'                          : u'Encuentro Popular y Social',
    u'esperanza federal'                                   : u'Esperanza Federal',
    u'federalismo santafesino'                             : u'Federalismo Santafesino',
    u'federalismo y liberacion'                            : u'Federalismo y Liberacion',
    u'federal santafesino'                                 : u'Federal Santafesino',
    u'frente civico - cordoba'                             : u'Frente Cívico - Córdoba',
    u'frente civico de la provincia de cordoba'            : u'Frente Civico de la Provincia de Cordoba',
    u'frente civico por santiago'                          : u'Frente Cívico por Santiago',
    u'frente civico y social de catamarca'                 : u'Frente Cívico y Social de Catamarca',
    u'frente del movimiento popular'                       : u'Frente del Movimiento Popular',
    u'frente de todos'                                     : u'Frente De Todos',
    u'frente justicia union y libertad - frejuli'          : u'Frente Justicia Unión y Libertad - FREJULI',
    u'frente para la victoria - partido bloquista'         : u'Frente para la Victoria - Partido Bloquista',
    u'frente para la victoria - pj'                        : u'Frente para la Victoria - PJ',
    u'frente peronista federal'                            : u'Frente Peronista Federal',
    u'frente popular bonaerense'                           : u'Frente Popular Bonaerense',
    u'frente por los derechos ciudadanos'                  : u'Frente por los Derechos Ciudadanos',
    u'frente produccion y trabajo'                         : u'Frente Producción y Trabajo',
    u'fza republicana'                                     : u'Fuerza Republicana',
    u'gen'                                                 : u'GEN',
    u'guardia peronista'                                   : u'Guardia Peronista',
    u'justicialismo republicano'                           : u'Justicialismo Republicano',
    u'justicialista 8 de octubre'                          : u'Justicialista 8 de Octubre',
    u'justicialista dialog ar'                             : u'Justicialista DIALOG AR',
    u'justicialista nacional'                              : u'Justicialista Nacional',
    u'justicialista para el dialogo de los argentinos'     : u'Justicialista para el Dialogo de los Argentinos',
    u'justicialista san luis'                              : u'Justicialista San Luis',
    u'justicialista'                                       : u'Justicialista',
    u'libres del sur'                                      : u'Libres del Sur',
    u'memoria y democracia'                                : u'Memoria y Democracia',
    u'movimiento independiente'                            : u'Movimiento Independiente',
    u'movimiento popular neuquino'                         : u'Movimiento Popular Neuquino',
    u'movimiento proyecto sur'                             : u'Movimiento Proyecto Sur',
    u'mov pop neuquino'                                    : u'Movimiento Popular Neuquino',
    u'nacional sindical'                                   : u'Nacional Sindical',
    u'no integra bloque'                                   : None,
    u'nuevo encuentro popular y solidario'                 : u'Nuevo Encuentro Popular y Solidario',
    u'partido de la concertacion - forja'                  : u'Partido de la Concertación - Forja',
    u'partido federal fueguino'                            : u'Partido Federal Fueguino',
    u'partido justicialista la pampa'                      : u'Partido Justicialista La Pampa',
    u'partido liberal de corrientes'                       : u'Partido Liberal de Corrientes',
    u'partido nuevo contra corrup. por honest. y transp.'  : u'Partido Nuevo contra Corrupción por la Honestidad y la Transparencia',
    u'partido nuevo'                                       : u'Partido Nuevo',
    u'partido renovador de salta'                          : u'Partido Renovador de Salta',
    u'partido socialista'                                  : u'Partido Socialista',
    u'peronismo federal'                                   : u'Peronismo Federal',
    u'peronismo jujeno'                                    : u'Peronismo Jujeño',
    u'peronista cordoba ciudadana'                         : u'Peronista Córdoba Ciudadana',
    u'peronista federal'                                   : u'Peronista Federal',
    u'peronista salteno'                                   : u'Peronista Salteño',
    u'peronista'                                           : u'Peronista',
    u'pj frente para la victoria'                          : u'PJ - Frente para la Victoria',
    u'por la verdad'                                       : u'Por la Verdad',
    u'por tierra del fuego'                                : u'Por Tierra del Fuego',
    u'produccion y trabajo'                                : u'Produccion y Trabajo',
    u'propuesta republicana'                               : u'Propuesta Republicana',
    u'pro'                                                 : u'PRO',
    u'proyecto buenos aires federal'                       : u'Proyecto Buenos Aires Federal',
    u'proyecto progresista'                                : u'Proyecto Progresista',
    u'recrear para el crecimiento'                         : u'Recrear para el Crecimiento',
    u'redes'                                               : u'Renovación y Desarrollo Social (REDES)',
    u'renovador de salta'                                  : u'Renovador de Salta',
    u'renovador'                                           : u'Renovador',
    u'salta somos todos'                                   : u'Salta Somos Todos',
    u'santa fe federal'                                    : u'Santa Fé Federal',
    u'si por la unidad popular'                            : u'SI por la Unidad Popular',
    u'social patagonico'                                   : u'Social Patagonico',
    u'solidaridad e igualdad (si) - ari (t.d.f.)'          : u'Solaridad e Igualdad (SI) - ARI (TDF)',
    u'solidaridad e igualdad (si) - proyecto progresista'  : u'Solaridad e Igualdad (SI) - Proyecto Progresista',
    u'solidaridad e igualdad (si)'                         : u'Solaridad e Igualdad (SI)',
    u'trabajo y dignidad'                                  : u'Trabajo y Dignidad',
    u'ucr'                                                 : u'Unión Civica Radical',
    u'unidad federalista'                                  : u'Unidad Federalista',
    u'union celeste y blanco'                              : u'Unión Celeste y Blanco',
    u'union civica radical'                                : u'Unión Civica Radical',
    u'union peronista'                                     : u'Unión Peronista',
    u'valores para mi pais'                                : u'Valores para mi País',
    u'vecinalista - partido nuevo'                         : u'Vecinalista - Partido Nuevo' }
